// <auto-generated />
namespace Bitcoin_Bonuses.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BonusType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BonusType));
        
        string IMigrationMetadata.Id
        {
            get { return "201407171815299_BonusType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
